version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-component-dispatcher-web:
    image: toposoid-component-dispatcher-web:0.1-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.12
      - PLAY_HTTP_PORT=9004
      - SENTENCE_PARSER_JP_WEB_HOST = 172.30.0.4
      - SENTENCE_PARSER_EN_WEB_HOST = 172.30.0.6
      - DEDUCTION_ADMIN_WEB_HOST=172.30.0.9
    networks:
      app_net:
        ipv4_address: 172.30.0.12
    ports:
      - 9004:9004
    depends_on:
      - toposoid-deduction-admin-web
      - toposoid-sentence-parser-japanese-web
      - toposoid-sentence-parser-english-web
  toposoid-deduction-admin-web:
    image: toposoid/toposoid-deduction-admin-web:0.1-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.9
      - PLAY_HTTP_PORT=9003
      - DEDUCTION_UNIT1_HOST=172.30.0.10
      - DEDUCTION_UNIT2_HOST=172.30.0.11
    networks:
      app_net:
        ipv4_address: 172.30.0.9
    ports:
      - 9003:9003
    depends_on:
      - toposoid-deduction-unit-exact-match-web
      - toposoid-deduction-unit-synonym-match-web
  toposoid-deduction-unit-exact-match-web:
    image: toposoid/toposoid-deduction-unit-exact-match-web:0.1-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.10
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9101
    networks:
      app_net:
        ipv4_address: 172.30.0.10
    ports:
      - 9101:9101
    depends_on:
      - scala-data-accessor-neo4j-web
  toposoid-deduction-unit-synonym-match-web:
    image: toposoid/toposoid-deduction-unit-synonym-match-web:0.1-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.11
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9102
    networks:
      app_net:
        ipv4_address: 172.30.0.11
    ports:
      - 9102:9102
    depends_on:
      - scala-data-accessor-neo4j-web
  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.1-SNAPSHOT
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.3
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9005:9005
    depends_on:
      - neo4j
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.1-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.4
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9001:9001
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.1-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.6
      - PLAY_HTTP_PORT=9007
      - CORENLP_HOST=172.30.0.8
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9007:9007
  corenlp:
    image: toposoid/corenlp:3.4.2
    networks:
      app_net:
        ipv4_address: 172.30.0.8
    ports:
      - 9000:9000
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2




