version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-component-dispatcher-web:
    image: toposoid-component-dispatcher-web:0.5-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.14
      - PLAY_HTTP_PORT=9004
      - TOPOSOID_GRAPHDB_HOST=172.30.0.2
      - TOPOSOID_GRAPHDB_WEB_HOST=172.30.0.3
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_HOST=172.30.0.4
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_PORT=9001
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_HOST=172.30.0.6
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_PORT=9007
      - TOPOSOID_COMMON_NLP_JP_WEB_HOST=172.30.0.5
      - TOPOSOID_COMMON_NLP_JP_WEB_PORT=9006
      - TOPOSOID_COMMON_NLP_EN_WEB_HOST=172.30.0.7
      - TOPOSOID_COMMON_NLP_EN_WEB_PORT=9008
      - TOPOSOID_DEDUCTION_ADMIN_WEB_HOST=172.30.0.20
      - TOPOSOID_DEDUCTION_ADMIN_WEB_PORT=9003
      - TOPOSOID_SAT_SOLVER_WEB_HOST=172.30.0.21
      - TOPOSOID_SAT_SOLVER_WEB_PORT=9009
      - TOPOSOID_DEDUCTION_ADMIN_SKIP=0
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_HOST=172.30.0.11
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_SENTENCE_VECTORDB_SEARCH_NUM_MAX=5
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_HOST=172.30.0.13
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_IMAGE_VECTORDB_SEARCH_NUM_MAX=5
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_HOST=172.30.0.10
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_PORT=9013
      - TOPOSOID_CONTENTS_ADMIN_HOST=172.30.0.9
      - TOPOSOID_CONTENTS_ADMIN_PORT=9012
    networks:
      app_net:
        ipv4_address: 172.30.0.22
    ports:
      - 9004:9004
  toposoid-sat-solver-web:
    image: toposoid/toposoid-sat-solver-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.21
      - PLAY_HTTP_PORT=9009
      - TOPOSOID_MAX_SAT_SOLVER=EvalMaxSAT_bin
      - TOPOSOID_CNF_FILE_PATH=/tmp
    networks:
      app_net:
        ipv4_address: 172.30.0.21
    ports:
      - 9009:9009
  toposoid-deduction-admin-web:
    image: toposoid/toposoid-deduction-admin-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.20
      - PLAY_HTTP_PORT=9003
      - TOPOSOID_DEDUCTION_UNIT1_HOST=172.30.0.15
      - TOPOSOID_DEDUCTION_UNIT1_PORT=9101
      - TOPOSOID_DEDUCTION_UNIT2_HOST=172.30.0.16
      - TOPOSOID_DEDUCTION_UNIT2_PORT=9102
      - TOPOSOID_DEDUCTION_UNIT3_HOST=172.30.0.17
      - TOPOSOID_DEDUCTION_UNIT3_PORT=9103
      - TOPOSOID_DEDUCTION_UNIT4_HOST=172.30.0.18
      - TOPOSOID_DEDUCTION_UNIT4_PORT=9104
      - TOPOSOID_DEDUCTION_UNIT5_HOST=172.30.0.19
      - TOPOSOID_DEDUCTION_UNIT5_PORT=9105
      - TOPOSOID_GRAPHDB_WEB_HOST=172.30.0.3
    networks:
      app_net:
        ipv4_address: 172.30.0.20
    ports:
      - 9003:9003
    depends_on:
      - toposoid-deduction-unit-exact-match-web
      - toposoid-deduction-unit-synonym-match-web
  toposoid-deduction-unit-exact-match-web:
    image: toposoid/toposoid-deduction-unit-exact-match-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.15
      - TOPOSOID_GRAPHDB_HOST=172.30.0.2
      - TOPOSOID_GRAPHDB_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9101
    networks:
      app_net:
        ipv4_address: 172.30.0.15
    ports:
      - 9101:9101
    depends_on:
      - scala-data-accessor-neo4j-web
  toposoid-deduction-unit-synonym-match-web:
    image: toposoid/toposoid-deduction-unit-synonym-match-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.16
      - TOPOSOID_GRAPHDB_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9102
    networks:
      app_net:
        ipv4_address: 172.30.0.16
    ports:
      - 9102:9102
    depends_on:
      - scala-data-accessor-neo4j-web
  toposoid-deduction-unit-sentence-vector-match-web:
    image: toposoid/toposoid-deduction-unit-sentence-vector-match-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.17
      - TOPOSOID_GRAPHDB_WEB_HOST=172.30.0.3
      - TOPOSOID_COMMON_NLP_JP_WEB_HOST=172.30.0.5
      - TOPOSOID_COMMON_NLP_JP_WEB_PORT=9006
      - TOPOSOID_COMMON_NLP_EN_WEB_HOST=172.30.0.7
      - TOPOSOID_COMMON_NLP_EN_WEB_PORT=9008
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_HOST=172.30.0.11
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_SENTENCE_VECTORDB_SEARCH_NUM_MAX=5
      - PLAY_HTTP_PORT=9103
    networks:
      app_net:
        ipv4_address: 172.30.0.17
    ports:
      - 9103:9103
    depends_on:
      - scala-data-accessor-neo4j-web
      - data-accessor-sentence-weaviate-web

  toposoid-deduction-unit-image-vector-match-web:
    image: toposoid/toposoid-deduction-unit-image-vector-match-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.18
      - TOPOSOID_GRAPHDB_WEB_HOST=172.30.0.3
      - TOPOSOID_COMMON_NLP_JP_WEB_HOST=172.30.0.5
      - TOPOSOID_COMMON_NLP_JP_WEB_PORT=9006
      - TOPOSOID_COMMON_NLP_EN_WEB_HOST=172.30.0.7
      - TOPOSOID_COMMON_NLP_EN_WEB_PORT=9008
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_HOST=172.30.0.11
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_SENTENCE_VECTORDB_SEARCH_NUM_MAX=5
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_HOST=172.30.0.13
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_IMAGE_VECTORDB_SEARCH_NUM_MAX=5
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_HOST=172.30.0.10
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_PORT=9013
      - PLAY_HTTP_PORT=9104
    networks:
      app_net:
        ipv4_address: 172.30.0.18
    ports:
      - 9104:9104
    depends_on:
      - scala-data-accessor-neo4j-web
      - toposoid-common-nlp-japanese-web
      - toposoid-common-nlp-english-web
      - data-accessor-sentence-weaviate-web
      - data-accessor-image-weaviate-web

  toposoid-deduction-unit-whole-sentence-image-match-web:
    image: toposoid/toposoid-deduction-unit-whole-sentence-image-match-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.19
      - TOPOSOID_GRAPHDB_WEB_HOST=172.30.0.3
      - TOPOSOID_COMMON_NLP_JP_WEB_HOST=172.30.0.5
      - TOPOSOID_COMMON_NLP_JP_WEB_PORT=9006
      - TOPOSOID_COMMON_NLP_EN_WEB_HOST=172.30.0.7
      - TOPOSOID_COMMON_NLP_EN_WEB_PORT=9008
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_HOST=172.30.0.11
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_SENTENCE_VECTORDB_SEARCH_NUM_MAX=5
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_HOST=172.30.0.13
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_IMAGE_VECTORDB_SEARCH_NUM_MAX=5
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_HOST=172.30.0.10
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_PORT=9013
      - PLAY_HTTP_PORT=9105
    networks:
      app_net:
        ipv4_address: 172.30.0.19
    ports:
      - 9105:9105

  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.3
      - TOPOSOID_GRAPHDB_HOST=172.30.0.2
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9005:9005
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.4
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9001:9001
  toposoid-common-nlp-japanese-web:
    image: toposoid/toposoid-common-nlp-japanese-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.5
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_JP=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_JP=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_JP=0.68
      - TOPOSOID_CHIVE_MODEL_VERSION=chive-1.2-mc90.kv
      - TOPOSOID_SENTENCEBERT_MODEL_JP=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - SENTENCE_TRANSFORMERS_HOME=./models
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9006:9006
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.6
      - PLAY_HTTP_PORT=9007
      - TOPOSOID_CORENLP_HOST=172.30.0.8
      - TOPOSOID_PARSER_SPACY_MODEL_EN=en_core_web_md
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9007:9007
  toposoid-common-nlp-english-web:
    image: toposoid/toposoid-common-nlp-english-web:0.5-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.7
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SPACY_MODEL_EN=en_core_web_md
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - SENTENCE_TRANSFORMERS_HOME=./models
      - PLAY_HTTP_PORT=9008
    networks:
      app_net:
        ipv4_address: 172.30.0.7
    ports:
      - 9008:9008
  corenlp:
    image: toposoid/corenlp:3.4.2-workflow
    networks:
      app_net:
        ipv4_address: 172.30.0.8
    ports:
      - 9000:9000
  neo4j:
    image: neo4j:4.4.23
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_transaction_timeout=10s
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/p@ssw0rd
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  toposoid-contents-admin-web:
    image: toposoid/toposoid-contents-admin-web:0.5-SNAPSHOT
    environment:
      - TOPOSOID_CONTENTS_URL=http://172.30.0.9:9012/contents/
    networks:
      app_net:
        ipv4_address: 172.30.0.9
    ports:
      - 9012:9012

  toposoid-common-image-recognition-web:
    image: toposoid/toposoid-common-image-recognition-web:0.5-SNAPSHOT-lowspec
    environment:
      - TOPOSOID_IMAGE_RECOGNITION_VIT_MODEL=google/vit-base-patch16-224
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_MODEL=apple/mobilevit-small
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_USE=1
    networks:
      app_net:
        ipv4_address: 172.30.0.10
    ports:
      - 9013:9013

  data-accessor-sentence-weaviate-web:
    image: toposoid/data-accessor-weaviate-web:0.5-SNAPSHOT
    environment:
      - TOPOSOID_WEAVIATE_HOST=172.30.0.12
      - TOPOSOID_WEAVIATE_PORT=8080
      - TOPOSOID_WEAVIATE_SIMILARITY_THRESHOLD=0.85
    networks:
      app_net:
        ipv4_address: 172.30.0.11
    ports:
      - 9020:9011
    depends_on:
      - sentence-weaviate
  sentence-weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.21.2
    ports:
      - 8080:8080
    networks:
      app_net:
        ipv4_address: 172.30.0.12
    #volumes:
    #  - /var/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      HUGGINGFACE_APIKEY: ''
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

  data-accessor-image-weaviate-web:
    image: toposoid/data-accessor-weaviate-web:0.5-SNAPSHOT
    environment:
      - TOPOSOID_WEAVIATE_HOST=172.30.0.14
      - TOPOSOID_WEAVIATE_PORT=8081
      - TOPOSOID_WEAVIATE_SIMILARITY_THRESHOLD=0.85
    networks:
      app_net:
        ipv4_address: 172.30.0.13
    ports:
      - 9021:9011
    depends_on:
      - image-weaviate

  image-weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8081'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.21.2
    ports:
      - 8081:8081
    networks:
      app_net:
        ipv4_address: 172.30.0.14
    #volumes:
    #  - /var/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      HUGGINGFACE_APIKEY: ''
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'