name: Test And Build
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-component-dispatcher-web
  PJ_BRANCH: main
  PJ_VERSION: 0.4
jobs:
  unit-test_toposoid-component-dispatcher-web:
    runs-on: self-hosted
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v3
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            cd ${GITHUB_WORKSPACE} && cd ../
            cd ./${{ env.PJ_REPO }}
            docker rm --force $(docker ps -a -q) > /dev/null 2>&1 && :
            docker rmi --force ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}-lowspec > /dev/null 2>&1 && :                              
            docker images
            docker system prune -f
            docker volume prune -f
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
            docker-compose -f docker-compose-workflow.yml up -d toposoid-component-dispatcher-web
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt headerCheck"
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt test:headerCheck"
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt compile"
            docker-compose -f docker-compose-workflow.yml up -d neo4j
            docker-compose -f docker-compose-workflow.yml up -d scala-data-accessor-neo4j-web
            docker-compose -f docker-compose-workflow.yml up -d sentence-weaviate
            docker-compose -f docker-compose-workflow.yml up -d data-accessor-sentence-weaviate-web
            docker-compose -f docker-compose-workflow.yml up -d image-weaviate
            docker-compose -f docker-compose-workflow.yml up -d data-accessor-image-weaviate-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-deduction-unit-exact-match-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-deduction-unit-synonym-match-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-deduction-unit-image-vector-match-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-deduction-unit-sentence-vector-match-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-deduction-unit-whole-sentence-image-match-web          
            docker-compose -f docker-compose-workflow.yml up -d toposoid-deduction-admin-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-sat-solver-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-japanese-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-japanese-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-contents-admin-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-common-image-recognition-web                    
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST http://localhost:7474
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*Japanese'"
            docker-compose -f docker-compose-workflow.yml rm -fsv toposoid-common-nlp-japanese-web
            docker-compose -f docker-compose-workflow.yml rm -fsv toposoid-sentence-parser-japanese-web
            docker-compose -f docker-compose-workflow.yml up -d corenlp
            docker-compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-english-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-english-web
            curl -X POST  -d 'Life is beautiful.' http://localhost:9000
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*English'"
            docker-compose -f docker-compose-workflow.yml down
            docker rmi --force ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}
      - name: Build And Push Docker Image For Test
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-lowspec
          push: true
          tags: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}-lowspec
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}
